### ISSUE TITLE
If only one venue is available to the org it should be selected by default on event creation

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-web#1389]

**Comment by Timo614** [comment]
@Krakaw just saw this comment: https://github.com/big-neon/bn-web/pull/1411#issuecomment-490122151

> We can still use the logic to automatically select the venue especially if the organization only has 1 venue attached to it, it can default to that one and display the public ones as options.

Do you mean that we should be filtering the list of venues down and automatically selecting any private venues if only one is available? Won't most private venues be upgraded to a public venue by an admin at a later time? So if an organization creates a private venue once we also will always automatically select even if they normally use public venues as well?

Just confirming since that's a bit different than the title here mentioned so want to confirm if that was the intent of this.

**Comment by Timo614** [comment]
I pushed up a PR with that adjustment per the comment and added you as a reviewer for it. Will track that change over there but thinking it over it does make sense given most smaller organizations may only deal with one venue that may never even go public.
