### ISSUE TITLE
Order refunds are showing face value not total value

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-web#1406]
The order amount is $11.00:
![image](https://user-images.githubusercontent.com/41575888/57175957-6d33dd80-6e52-11e9-929b-36825d7c51d6.png)
When I choose a ticket to refund I am not seeing the per ticket fee value included.
![image](https://user-images.githubusercontent.com/41575888/57175974-ac622e80-6e52-11e9-9a45-cb16897f4be0.png)

**Comment by mikethetike** [comment]
@harrisonlemon @zmelamed The problem here is that the event fees are at an order level, but we can refund tickets individually. 

How can we solve this?
Option 1: Add the event fee into the refund amount when all of the tickets are selected in the current Manage Orders screen. We should probably add a UI hint (e.g. Refund 2x$10 + 1x$1 event fee)
Option 2: Add a Refund at an order level. This would require a new screen, or adding new elements to the existing order screen

**Comment by harrisonlemon** [comment]
@mikethetike @zmelamed This might be a good time to start thinking about the future of orders & which direction we want to go. Will we support the ability to purchase multiple events within the same transaction? If yes, we might want to consider refunds on an order-level (rather than an event-level) because of the possible per-order fee implications & customer management flow. 

Additionally: the ultimate end-goal is to be able to specify which elements of the order to refund. For example: a user should be able to refund ONLY the fees, ONLY the base, or Base + Fees. 

Here are 2 screenshots of the refund flow in Ticketfly in case this is helpful: 

![rtaImage (3)](https://user-images.githubusercontent.com/49532549/57336018-18aa8f80-70ea-11e9-85f0-49e2232c00f3.jpeg)

![rtaImage (2)](https://user-images.githubusercontent.com/49532549/57336030-219b6100-70ea-11e9-85ac-a9a89baca716.jpeg)

**Comment by mikethetike** [comment]
I agree that you should be able to select all the items on an order and decide which ones we should refund. With the latest changes this is now possible, but we need some UI designs to facilitate

**Comment by harrisonlemon** [comment]
Thx @mikethetike! @zmelamed Let me know if I can help with the design

**Comment by zmelamed** [comment]
These are well underway and I believe you're attached to the related tickets in asana. The UI and spec will be included with other order management spec and we'll review together @harrisonlemon

**Comment by mikethetike** [comment]
Closing this because there are other issues that deal with this
