### ISSUE TITLE
Fan Profile Management: Redesign: Activity Items: Purchased

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1506]
- [ ] [Purchasing User Name] purchased [# tickets] to [Event Name]
- [ ] If tickets to multiple events are purchased in the same order each should have it's own purchase item like "Sam Johnson purchased 3 Tickets to Ariana Grande..."
- [ ] Expanded View
 - Event Venue
 - Name, City, State
 - Event Date and Time
 - Code Used in order (Code, Type, Discount Amount if any)
 - Total Tickets included in Order for Event
 - Order Total for related event
 - (Refunded amount if any)
 - CTA: View Order which links to Order Management View

**Comment by Anziskavds** [comment]
Tested on develop and tested unsuccessful in some of the fields.

Steps to reproduce:

- Instead of [Purchasing User Name] purchased [# tickets] to [Event Name] it shows as follow Purchased [# tickets] to [Event Name] **(Order #)** https://cl.ly/6c4fa07c64a3
- Purchase Expanded View: Code Used in order (Code, **Type**, Discount Amount if any) everything appears except for the Type https://cl.ly/8f52a7a63da2
- Purchase: (Refunded amount if any), the refund amount does not reflect under the purchase expanded view https://cl.ly/01d1bcfb8736 https://cl.ly/e968594047b7

**Comment by Anziskavds** [comment]
- Tested on develop and found that when a discount code is used to purchase a ticket the discount fee is not correct.

- Ticket price is $10, discount is $5. Discount fee should show $5. I also don't know why $1.06 shows under discount. 

@shanimal08 Use discount in cents instead of total in cents.

https://cl.ly/e6bab69fbc8a

**Comment by Anziskavds** [comment]
Tested successful on develop for web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

**Comment by Anziskavds** [comment]
Tested successful on Prod for web and mobile web.
