### ISSUE TITLE
Report verifications: Event Audit, event summary audit

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-web#1592]
Issue experienced where "Guest list" tickets were sold from the 'Guest list', smart-hold at the box office, however when the event audit and the event audit summary reports were viewed, the tickets displayed as "Online sales" as opposed to "Box Office" sales.

To test:
Purchase free tickets from Smart Hold
Purchase Box Office tickets
View the above mentioned reports
Verify these tickets are displayed as "Box Office" sales and not "Online sales"

**Comment by Anziskavds** [comment]
@Tas4tari Tested and noticed that if you purchase tickets with a Comp redemption code it will only calculate the total amount of comp tickets sold and will be 0 on Box office and 0 on Online. Please advise if this is the expected behaviour? 

Sold tickets with a discount redemption code calculates correctly on how many was sold on from Box office and how many was sold online.

Seems like it is only on the comps that it doesn't show how many was sold from the Box office and how many was sold online.

https://cl.ly/d35284dc85b1

**Comment by Tas4tari** [comment]
@Krakaw Can you please advise if the above is expected behaviour

**Comment by Anziskavds** [comment]
@Krakaw @Tas4tari Any feedback yet on the expected behaviour on this issue?

**Comment by Anziskavds** [comment]
Tested on Beta the report shows the correct information as expected

**Comment by Anziskavds** [comment]
Tested on Prod and the report shows the correct information as expected

https://cl.ly/fa26111d64ff
