### ISSUE TITLE
Box Office Holds - Names from the hold list should not appear in the sell view as a hold, they should appear in the guest list section

### ISSUE THREAD

**Issue by zmelamed** [big-neon/bn-web#572]
[https://www.bugherd.com/projects/154576/tasks/9](https://www.bugherd.com/projects/154576/tasks/9)

**Comment by Jasonvdb** [comment]
@zmelamed how should we be distinguishing between a hold and a hold for a specific person? At the moment the reason it shows up under the sales section is because it's just seen as a normal hold and I can't tell if it's someone's name or not. There's nothing that attaches it to a user.

At the moment these 2 holds are seen the same way even though one is a name:
![screenshot 2018-12-12 at 08 31 32](https://user-images.githubusercontent.com/5300488/49851030-71e6ef00-fde8-11e8-8eb8-de7325fc4998.png)

**Comment by Jasonvdb** [comment]
If they need to be separated we might need to set an additional flag when setting up called 'guestlist' or something

**Comment by zmelamed** [comment]
There should be a data point available associating a name with a list, if a hold has a parent list associated with it it shouldn’t be exposed  as a primary hold list in the sell view. If a hold has a parent associated with it and a name it should be searchable in the guest list view.

@krakaw, It’s possible to view names that are on a specific hold in the holds management section of studio, so that association exists in the backend, it may just need to be exposed to the client in box office? Can’t there be two separate calls, 1 to get what the industry would consider “holds” (which would be any hold as we define them in our system without a parent list), and one to get names on the list (which would be any hold that had a parent hold id attribute in our system)

The industry doesn’t recognize the names on the hold as separate holds, we need to abstract away the implementation details from the experience here.

**Comment by Jasonvdb** [comment]
Makes sense, will chat to @Krakaw and @mikethetike and see how we can do that

**Comment by mikethetike** [comment]
I agree that these should not be in the holds section, but I'm not sure where exactly the best place to solve this is. 

The problem is that the names on the list, as we currently have implemented, are reserved, but not sold. 

So they can't be on the guest list because the ticket needs to be checked out somewhere. 

We can solve this by checking out the actual tickets when adding a name to a list. This can only be done for Comps, discounts there has to be some kind of payment. Perhaps we could disable name lists for discounts? 

The access code on the comp then also becomes irrelevant.

**Comment by zmelamed** [comment]
The original design was to have the Guest list section accommodate the ability to not just check-in but fulfill orders for paid/discounted holds reusing some of the same logic as the sell view... please take a look at this mock and let me know if this adds any clarity. (the filtering of the guest list view can come later if needed) Wanted to try and help visualize where we want to get with this:
![unified-guest-list-overview](https://user-images.githubusercontent.com/456953/50568453-ee456180-0d06-11e9-83f2-a378c180916e.png)

**Comment by Jasonvdb** [comment]
If a hold has a parent ID, include it in the guest list
